### ISSUE TITLE
Flutter Support 

### ISSUE THREAD

**Issue by Abdelrhman9623** [Clivern/Beaver#135]
i am trying to connect to beaver server with webscket first i try it with basic connection soket server is working with me but when i try it with beaver thats what happened

I/flutter ( 1396): AsyncSnapshot<dynamic>(ConnectionState.done, null, WebSocketChannelException: WebSocketChannelException: WebSocketException: Connection to 'https://go-beaver-k8s-1.nimi24.com:0/#' was not upgraded to websocket) 

That issue its need config in flutter or from beaver server ??

Also i send token to server url and token inside header
IOWebSocketChannel.connect(
          'ws://go-beaver****',
          headers: {'token': ''}
        ),
Thats it.

**Comment by Clivern** [comment]
I am not expert with flutter but from the error `Connection to 'https://$$$$' was not upgraded to websocket`, it seems your code still doing HTTP connection & need to upgrade to WebSockets. I think it can be done by sending these headers

```
Connection: Upgrade
Upgrade: websocket
```

Please check these info https://developer.mozilla.org/en-US/docs/Web/HTTP/Protocol_upgrade_mechanism#Upgrading_to_a_WebSocket_connection

I checked this website `wss://echo.websocket.org/` and i see these header in the request & server response so maybe i have to add these headers in beaver response if sending the headers solely won't help. so pls let me know!


<img width="779" alt="Screen Shot 2020-12-29 at 7 26 47 PM" src="https://user-images.githubusercontent.com/1634427/103305604-d5faa100-4a0b-11eb-923f-5a694fbc6ea6.png">

**Comment by Abdelrhman9623** [comment]
IOWebSocketChannel.connect('wss://go-beaver-k8s-1.nimi24.com/',
            headers: {
              'token': '',
              'Connection': 'Upgrade',
              'Upgrade': 'websocket',
            }),
the same issue 
I/flutter ( 3355): AsyncSnapshot<dynamic>(ConnectionState.done, null, WebSocketChannelException: WebSocketChannelException: WebSocketException: Connection to 'https://go-beaver-k8s-1.nimi24.com:0/#' was not upgraded to websocket)

**Comment by Clivern** [comment]
Well that's interesting because beaver already add these headers https://github.com/gorilla/websocket/blob/c3dd95aea9779669bb3daafbd84ee0530c8ce1c1/server.go#L217

I just tested that.

What is the URL y use to connect as a client, it should be something like 
`wss://go-beaver-k8s-1.nimi24.com/ws/$$CLIENT_ID$$/$$CLIENT_TOKEN$$`

so i assume you use `IOWebSocketChannel.connect('wss://go-beaver-k8s-1.nimi24.com/ws/~client-id~/~client-token~',`?
token not need in headers actually

and to create a client id and token

```
$ curl -X POST \
    -H 'Content-Type: application/json' \
    -H 'X-AUTH-TOKEN: YOUR-API-TOKEN-HERE' \
    -d '{"channels": []}' \
    'https://go-beaver-k8s-1.nimi24.com/api/client'

{
  "channels": [],
  "created_at": 1609269864,
  "id": "0de46431-af57-4768-8d2d-14b8c07a1f0b",
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiMGRlNDY0MzEtYWY1Ny00NzY4LThkMmQtMTRiOGMwN2ExZjBiQDE2MDkyNjk4NjQiLCJ0aW1lc3RhbXAiOjE2MDkyNjk4NjR9.1vNZ20Ehj-OeFDPIF21QN84a-mip4F5ZMTKLahvk1iw",
  "updated_at": 1609269864
}
```

I am trying to know if it is issue with flutter or not. so can you try to init a websocket from browser > inspect > Console, don't forget to replace client id and token.

```js
function Socket(url){
    ws = new WebSocket(url);
    ws.onmessage = function(e) { console.log(e); };
    ws.onclose = function(){
        // Try to reconnect in 5 seconds
        setTimeout(function(){Socket(url)}, 5000);
    };
}

Socket('wss://go-beaver-k8s-1.nimi24.com/ws/~client-id~/~client-token~');
```
