### ISSUE TITLE
from_client is null

### ISSUE THREAD

**Issue by zkbqhuang** [Clivern/Beaver#145]
hi Clivern!
The from_client is null when I use PublishChannel func of beavergo client tool, and I got result from vuejs frontend like this:
`{"from_client":"","to_client":"474a1d7f-ba2a-4131-afcd-452a8dd04d11","channel":"app_x_chatroom_1","data":"{\"message\":\"555\\n\"}"}`
so how to know the message came from which client in a chatroom app?

**Comment by Clivern** [comment]
Hi @zkbqhuang,

I am not sure if it is a bug in beaver or the package https://github.com/domgolonka/beavergo. so it will be investigation then

**Comment by Clivern** [comment]
from_client is null since it is from api
