### ISSUE TITLE
[beaver.http] test beaver on vscode

### ISSUE THREAD

**Issue by gozeon** [Clivern/Beaver#54]
the  file with [vscode-restclient](https://github.com/Huachao/vscode-restclient), [see file](https://gist.github.com/gozeon/e493fe177c1cc454f71cceebd5d6a46c)

**Comment by gozeon** [comment]
Sorry, I don't know if this issure belongs to issure or pr, I am very sorry.

**Comment by Clivern** [comment]
Yes it belongs to PR but may be on a community section
