### ISSUE TITLE
Don't handle error when create file log

### ISSUE THREAD

**Issue by andrewvo148** [Clivern/Beaver#81]
https://github.com/Clivern/Beaver/blob/d66531be70a3debbf54046cdbcb4a8677966ee98/beaver.go#L58

**Comment by andrewvo148** [comment]
If log.path doesn't exists it will silent failure, so i think should handle error.

**Comment by Clivern** [comment]
You are indeed right @andrewvo148, I should do panic in this case. 
If you wanna update this, would be nice otherwise i will do that

**Comment by andrewvo148** [comment]
@Clivern  . I very happy to make it
